title: "瑛甸"
description: "A Jekyll theme based on MDUI"
url: 
baseurl: ""
author: "MinzChan"
paginate: 6
paginate_path: "/blog/page:num/"

theme: jekyll-theme-mdui

gems:
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs